# -*- coding: utf-8 -*-
"""Copy of Lab4DMW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1joXPaHzO1ju6AllydOrAW8nWCygOJHf3
"""

#question 1

import pandas as pd

#dataset
data = {
    "Employee ID": [20005, 20006, 20007, 20008, 20009, 20010, 20011, 20012],
    "Date of Join": ["05-01-2019", "10-01-2019", "01-02-2019", "05-02-2019", "01-03-2019", "02-03-2019", "02-04-2019", "05-04-2019"]
}

df = pd.DataFrame(data)

#date column to datetime
df["Date of Join"] = pd.to_datetime(df["Date of Join"], format="%d-%m-%Y")

# format in year, month, and day
df["Year"] = df["Date of Join"].dt.year
df["Month"] = df["Date of Join"].dt.month
df["Day"] = df["Date of Join"].dt.day

df = df.drop(columns=["Date of Join"])  #original date column
print("Preprocessed Data:")
print(df)

#for question 2
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

#dataset
data_normalization = {
    "Col A": [180000, 360000, 230000, 60000],
    "Col B": [110, 905, 230, 450],
    "Col C": [18.9, 23.4, 14.0, 13.5],
    "Col D": [1400, 1800, 1300, 1500]
}

df_norm = pd.DataFrame(data_normalization)

# applying min-max normalization
scaler = MinMaxScaler()
df_norm_scaled = pd.DataFrame(scaler.fit_transform(df_norm), columns=df_norm.columns)

print("Min-Max Normalized Data:")
print(df_norm_scaled)